### ISSUE TITLE
Traversing Folders

### ISSUE THREAD

**Issue by pixel5919** [iankronquist/senior-project-experiment#6]
Currently, traversing a single folder works with znotify.c  (-t) but with multiple there is an error. Option (-w) works with multiple command line arguments though.

**Comment by pixel5919** [comment]
Fixed with `static int walker(const char *pathname, const struct stat *sbuf,
                int type,struct FTW *ftwb)
{
        if(sbuf->st_mode & FTW_DP)
        {
                return watch_this(pathname);
        }
        else if(sbuf->st_mode & FTW_DNR)
        {
                fprintf(stderr,"\nCan't Read: %s",pathname);
                return -1;
        }
}`

**Comment by pixel5919** [comment]
Fixed with 
`static int walker(const char *pathname, const struct stat *sbuf,
                int type,struct FTW *ftwb)
{
        if(sbuf->st_mode & FTW_DP)
        {
                return watch_this(pathname);
        }
        else if(sbuf->st_mode & FTW_DNR)
        {
                fprintf(stderr,"\nCan't Read: %s",pathname);
                return -1;
        }
}`

**Comment by pixel5919** [comment]
This is the error message: 

Error Occured Adding to Watch List: /usr/lib/python3/dist-packages/DistUpgrade/NvidiaDetector No such file or directory

Command Line: `./a.out -e -t /usr/bin /usr/lib`

**Comment by iankronquist** [comment]
I'll take a look. Seems odd.

**Comment by iankronquist** [comment]
Cannot reproduce in the vagrant vm. Have you installed any interesting python packages?
What is the output of `pip freeze`?

**Comment by pixel5919** [comment]
`PyYAML==3.11
apt-xapian-index==0.45
argparse==1.2.1
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.0
chardet==2.0.1
colorama==0.2.5
docker-compose==1.6.0
docker-py==1.7.0
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.2
functools32==3.2.3-2
html5lib==0.999
jsonschema==2.5.1
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
requests==2.7.0
six==1.5.2
ssh-import-id==3.21
texttable==0.8.4
urllib3==1.7.1
websocket-client==0.35.0
wheel==0.24.0
wsgiref==0.1.2`

**Comment by pixel5919** [comment]
I actually "fixed" the problem. Many of the "directories" that were getting traversed were actually symlinks. I told the program to ignore them and it works so far. 

My issue with this quick fix is that if someone redirects those symlinks, I believe the program can catch it with the folder above it catching the event.
